/* =========================================================
   Cognitive experience taxonomy
   For every question type: what CONCEPT it teaches, which THINKING SKILL it uses,
   which ARCHETYPE (way of asking) it is, which FAMILY of related concepts it belongs to,
   and whether it carries an "aha" (a trick or insight worth teaching).
   The Experience Director uses this to vary what the player actually experiences,
   not just the numbers.
   ========================================================= */

// Thinking skills (how the brain is asked to work)
export const SKILLS = {
  recall: 'Recall', mental: 'Mental math', calc: 'Calculation', estimate: 'Estimation', pattern: 'Pattern spotting',
  compare: 'Comparison', eliminate: 'Elimination', deduce: 'Deduction', reverse: 'Reverse reasoning', multistep: 'Multi-step reasoning',
  spatial: 'Spatial reasoning', constraint: 'Constraint solving', data: 'Reading data', reading: 'Critical reading', inference: 'Inference',
  shortcut: 'Shortcut spotting', trap: 'Trap detection',
};
// Archetypes (how the question is asked)
export const ARCHS = {
  solve: 'Solve it', missing: 'Find the missing value', reverse: 'Work backwards', mustTrue: 'What must be true', closest: 'Closest value',
  compare: 'Which is bigger', mistake: 'Spot the mistake', conclusion: 'What follows', odd: 'Odd one out', pattern: 'Complete the pattern',
  sufficient: 'Is it enough?', convert: 'Convert it', arrange: 'Arrange it', meaning: 'What it means', count: 'Count it', locate: 'Where is it',
};
export const FAMILIES = {
  pct: 'Percentages & money', ratio: 'Ratios & sharing', avg: 'Averages & statistics', interest: 'Interest', work: 'Work & pipes', motion: 'Speed & motion',
  number: 'Numbers & mental maths', algebra: 'Algebra & sequences', geometry: 'Geometry & mensuration', chance: 'Counting & probability',
  series: 'Series & patterns', coding: 'Coding', relations: 'Relations & directions', arrangement: 'Puzzles & arrangements', deduction: 'Deduction',
  time: 'Clocks & calendars', di: 'Data interpretation', vocab: 'Vocabulary', grammar: 'Grammar & usage', reading: 'Reading', figures: 'Figure patterns', space: 'Space & counting',
};

// id: [concept name, skill, archetype, family, aha]
const T = {
  'q.mental': ['Mental arithmetic', 'mental', 'solve', 'number', 1],
  'q.approx': ['Approximation', 'estimate', 'closest', 'number', 0],
  'q.fraction': ['Comparing fractions', 'compare', 'compare', 'number', 0],
  'q.pct.of': ['Percent of a number', 'calc', 'solve', 'pct', 0],
  'q.pct.what': ['What percent is it', 'calc', 'missing', 'pct', 0],
  'q.pct.change': ['Percentage change', 'calc', 'solve', 'pct', 0],
  'q.pct.succ': ['Successive changes', 'shortcut', 'solve', 'pct', 1],
  'q.pct.rev': ['Original before a change', 'reverse', 'reverse', 'pct', 0],
  'q.pct.pop': ['Compound growth', 'multistep', 'solve', 'pct', 0],
  'q.pct.frac': ['Percent–fraction shortcuts', 'shortcut', 'convert', 'pct', 1],
  'q.pct.trap': ['Percentage traps', 'trap', 'mustTrue', 'pct', 1],
  'q.pl.sp': ['Selling price', 'calc', 'solve', 'pct', 0],
  'q.pl.pct': ['Profit percent', 'calc', 'missing', 'pct', 0],
  'q.pl.cp': ['Cost price from selling price', 'reverse', 'reverse', 'pct', 1],
  'q.disc': ['Discounts', 'calc', 'solve', 'pct', 0],
  'q.disc.succ': ['Successive discounts', 'shortcut', 'solve', 'pct', 1],
  'q.disc.markup': ['Mark-up then discount', 'multistep', 'solve', 'pct', 0],
  'q.spot.step': ['Spot the wrong step', 'trap', 'mistake', 'pct', 1],
  'q.ratio.share': ['Sharing in a ratio', 'calc', 'solve', 'ratio', 0],
  'q.ratio.comb': ['Combining ratios', 'deduce', 'solve', 'ratio', 0],
  'q.ratio.add': ['Changing a ratio', 'reverse', 'missing', 'ratio', 0],
  'q.partner': ['Partnership profit', 'multistep', 'solve', 'ratio', 0],
  'q.mix.allig': ['Alligation', 'shortcut', 'solve', 'ratio', 1],
  'q.mix.water': ['Diluting mixtures', 'multistep', 'missing', 'ratio', 0],
  'q.ages': ['Age sums & differences', 'calc', 'solve', 'ratio', 0],
  'q.ages.ratio': ['Ages in ratio over time', 'multistep', 'reverse', 'ratio', 0],
  'q.avg': ['Averages', 'calc', 'solve', 'avg', 0],
  'q.avg.new': ['New member joins', 'reverse', 'missing', 'avg', 1],
  'q.stats': ['Median, mode & range', 'recall', 'solve', 'avg', 0],
  'q.si': ['Simple interest', 'calc', 'solve', 'interest', 0],
  'q.si.rate': ['Finding the rate', 'reverse', 'reverse', 'interest', 0],
  'q.ci': ['Compound interest', 'multistep', 'solve', 'interest', 0],
  'q.ci.diff': ['CI − SI shortcut', 'shortcut', 'solve', 'interest', 1],
  'q.work.tog': ['Working together', 'calc', 'solve', 'work', 0],
  'q.work.alone': ['One worker alone', 'reverse', 'reverse', 'work', 0],
  'q.work.eff': ['Efficiency ratios', 'deduce', 'solve', 'work', 1],
  'q.pipes': ['Pipes & leaks', 'calc', 'solve', 'work', 0],
  'q.tsd': ['Speed, distance, time', 'calc', 'solve', 'motion', 0],
  'q.tsd.units': ['km/h to m/s', 'shortcut', 'convert', 'motion', 1],
  'q.tsd.avg': ['Average speed trap', 'trap', 'solve', 'motion', 1],
  'q.train.pole': ['Trains & platforms', 'multistep', 'solve', 'motion', 0],
  'q.train.rel': ['Relative speed', 'multistep', 'solve', 'motion', 0],
  'q.boat': ['Boats & streams', 'deduce', 'reverse', 'motion', 1],
  'q.race': ['Races', 'multistep', 'solve', 'motion', 1],
  'q.num.unit': ['Unit digit cycles', 'pattern', 'solve', 'number', 1],
  'q.num.rem': ['Remainders', 'pattern', 'solve', 'number', 1],
  'q.num.div': ['Divisibility rules', 'shortcut', 'eliminate', 'number', 1],
  'q.num.hcf': ['HCF & LCM', 'calc', 'solve', 'number', 0],
  'q.num.bells': ['Meeting again (LCM)', 'deduce', 'solve', 'number', 0],
  'q.num.factors': ['Counting factors', 'shortcut', 'count', 'number', 1],
  'q.num.zeros': ['Trailing zeros', 'shortcut', 'count', 'number', 1],
  'q.num.sumn': ['Sum formulas', 'recall', 'solve', 'number', 1],
  'q.simplify': ['BODMAS', 'calc', 'solve', 'number', 0],
  'q.roots': ['Roots by last digit', 'shortcut', 'reverse', 'number', 1],
  'q.indices': ['Powers & indices', 'deduce', 'missing', 'algebra', 0],
  'q.trick': ['Mental-math tricks', 'shortcut', 'solve', 'number', 1],
  'q.compare.vals': ['Which is biggest?', 'compare', 'compare', 'number', 0],
  'q.alg.lin': ['Linear equations', 'calc', 'missing', 'algebra', 0],
  'q.alg.sys': ['Two equations', 'shortcut', 'solve', 'algebra', 1],
  'q.alg.quad': ['Quadratic roots', 'deduce', 'solve', 'algebra', 0],
  'q.quad.compare': ['Comparing roots', 'compare', 'compare', 'algebra', 0],
  'q.alg.ineq': ['Inequalities', 'deduce', 'missing', 'algebra', 0],
  'q.alg.func': ['Functions', 'multistep', 'solve', 'algebra', 0],
  'q.log': ['Logarithms', 'recall', 'solve', 'algebra', 0],
  'q.ap.nth': ['AP nth term', 'pattern', 'solve', 'algebra', 0],
  'q.ap.sum': ['AP sum', 'calc', 'solve', 'algebra', 0],
  'q.gp': ['GP terms', 'pattern', 'solve', 'algebra', 0],
  'q.geo.ang': ['Angles', 'recall', 'solve', 'geometry', 0],
  'q.geo.pyth': ['Pythagoras', 'shortcut', 'solve', 'geometry', 1],
  'q.mens.rect': ['Rectangles', 'reverse', 'solve', 'geometry', 0],
  'q.mens.circle': ['Circles', 'calc', 'solve', 'geometry', 0],
  'q.mens.solid': ['Solids', 'calc', 'solve', 'geometry', 0],
  'q.mens.more': ['Triangles, cones, spheres', 'calc', 'solve', 'geometry', 0],
  'q.coord': ['Coordinate geometry', 'calc', 'solve', 'geometry', 0],
  'q.pnc.arr': ['Arrangements with repeats', 'shortcut', 'count', 'chance', 1],
  'q.pnc.comm': ['Selections', 'multistep', 'count', 'chance', 0],
  'q.prob.dice': ['Dice probability', 'calc', 'count', 'chance', 0],
  'q.prob.balls': ['Drawing balls', 'multistep', 'solve', 'chance', 0],
  'q.prob.coins': ['Coins & "at least"', 'shortcut', 'solve', 'chance', 1],
  'q.prob.cards': ['Cards', 'recall', 'count', 'chance', 0],
  'q.prob.intuition': ['Probability intuition', 'trap', 'mustTrue', 'chance', 1],
  'q.sets': ['Sets & Venn', 'deduce', 'solve', 'chance', 0],
  'l.series.num': ['Number series', 'pattern', 'pattern', 'series', 0],
  'l.series.wrong': ['Wrong term in a series', 'pattern', 'mistake', 'series', 0],
  'l.series.letter': ['Letter series', 'pattern', 'pattern', 'series', 0],
  'l.series.alnum': ['Letter-number series', 'pattern', 'pattern', 'series', 0],
  'l.analogy.num': ['Number analogy', 'pattern', 'missing', 'series', 0],
  'l.odd.num': ['Odd number out', 'eliminate', 'odd', 'series', 0],
  'l.code': ['Coding-decoding', 'pattern', 'solve', 'coding', 0],
  'l.blood': ['Blood relations', 'deduce', 'conclusion', 'relations', 0],
  'l.dir.turn': ['Turning directions', 'spatial', 'locate', 'relations', 0],
  'l.dir.dist': ['Net displacement', 'spatial', 'locate', 'relations', 1],
  'l.rank.pos': ['Position in a row', 'shortcut', 'solve', 'relations', 1],
  'l.rank.order': ['Ordering people', 'deduce', 'conclusion', 'relations', 0],
  'l.seat.linear': ['Linear seating', 'constraint', 'arrange', 'arrangement', 0],
  'l.seat.circular': ['Circular seating', 'constraint', 'arrange', 'arrangement', 0],
  'l.schedule': ['Scheduling', 'constraint', 'arrange', 'arrangement', 0],
  'l.distribution': ['Two-attribute puzzles', 'constraint', 'arrange', 'arrangement', 0],
  'l.select': ['Team selection', 'eliminate', 'mustTrue', 'arrangement', 0],
  'l.syl.quick': ['Syllogism check', 'deduce', 'mustTrue', 'deduction', 0],
  'l.syl': ['Syllogisms', 'deduce', 'conclusion', 'deduction', 0],
  'l.ds': ['Data sufficiency', 'inference', 'sufficient', 'deduction', 0],
  'l.cond': ['If-then logic', 'trap', 'mustTrue', 'deduction', 1],
  'l.critical': ['Strong arguments', 'reading', 'conclusion', 'deduction', 0],
  'l.ineq': ['Coded inequalities', 'deduce', 'conclusion', 'deduction', 1],
  'l.clock': ['Clock angles', 'shortcut', 'solve', 'time', 1],
  'l.clock.mirror': ['Mirror clocks', 'shortcut', 'reverse', 'time', 1],
  'l.calendar': ['Calendars', 'pattern', 'solve', 'time', 0],
  'd.bar.quick': ['Reading bar charts', 'data', 'locate', 'di', 0],
  'd.bar.pct': ['Percent change from charts', 'data', 'solve', 'di', 0],
  'd.table': ['Tables', 'data', 'compare', 'di', 0],
  'd.line': ['Line graphs', 'data', 'solve', 'di', 0],
  'd.pie': ['Pie charts', 'data', 'convert', 'di', 1],
  'd.caselet': ['Caselets', 'multistep', 'solve', 'di', 0],
  'd.missing': ['Missing data', 'reverse', 'missing', 'di', 0],
  'd.compare': ['Comparing two series', 'compare', 'compare', 'di', 0],
  'd.multi': ['Multi-step DI', 'multistep', 'solve', 'di', 0],
  'v.syn': ['Synonyms', 'recall', 'meaning', 'vocab', 0],
  'v.ant': ['Antonyms', 'recall', 'meaning', 'vocab', 0],
  'v.vocab': ['Word meanings', 'recall', 'meaning', 'vocab', 0],
  'v.oneword': ['One-word substitution', 'recall', 'meaning', 'vocab', 0],
  'v.idiom': ['Idioms', 'inference', 'meaning', 'vocab', 0],
  'v.spell': ['Spelling', 'trap', 'eliminate', 'vocab', 0],
  'v.analogy': ['Word analogies', 'pattern', 'missing', 'grammar', 0],
  'v.complete': ['Sentence completion', 'inference', 'missing', 'grammar', 0],
  'v.error': ['Error spotting', 'trap', 'mistake', 'grammar', 0],
  'v.jumble': ['Para jumbles', 'reading', 'arrange', 'reading', 0],
  'v.rc': ['Reading comprehension', 'reading', 'conclusion', 'reading', 0],
  'g.figseries': ['Figure series', 'pattern', 'pattern', 'figures', 0],
  'g.figana': ['Figure analogy', 'pattern', 'missing', 'figures', 0],
  'g.figodd': ['Odd figure out', 'eliminate', 'odd', 'figures', 0],
  'g.pattern': ['Repeating patterns', 'pattern', 'pattern', 'figures', 0],
  'g.matrix': ['Number matrices', 'pattern', 'missing', 'figures', 0],
  'g.magic': ['Magic squares', 'deduce', 'missing', 'figures', 0],
  'g.emoji': ['Symbol equations', 'deduce', 'missing', 'figures', 0],
  'g.mirror': ['Mirror & water images', 'spatial', 'solve', 'space', 0],
  'g.arrows': ['Rotations', 'spatial', 'solve', 'space', 0],
  'g.dice': ['Dice opposite faces', 'spatial', 'eliminate', 'space', 1],
  'g.cube': ['Painted cubes', 'spatial', 'count', 'space', 1],
  'g.fold': ['Paper folding', 'spatial', 'count', 'space', 1],
  'g.squares': ['Counting squares', 'shortcut', 'count', 'space', 1],
  'g.count': ['Visual counting', 'recall', 'count', 'space', 0],
};

export const TAXO = Object.fromEntries(Object.entries(T).map(([id, [name, skill, arch, family, aha]]) => [id, { id, name, skill, arch, family, aha: !!aha }]));
export const taxoOf = (tid) => TAXO[tid] || { id: tid, name: tid, skill: 'calc', arch: 'solve', family: 'number', aha: false };
