/* One exam shortcut per topic. Shown with full solutions (Long, Train) and in the
   "Learn from this game" review, so every mistake leaves the player a trick they can reuse. */
export const TIPS = {
  // Quant
  'Mental math': '× 25 = × 100 ÷ 4 · × 11: write the digits and put their sum in the middle (36 × 11 = 3|9|6) · × 5 = × 10 ÷ 2.',
  Approximation: 'Round every number to something friendly first (75.1% → 75% = ¾, 1102 → 1100), then pick the closest option.',
  Fractions: 'To compare a/b and c/d, cross-multiply: a×d vs c×b. Bigger cross product = bigger fraction.',
  Simplification: 'BODMAS: Brackets → Of → Division/Multiplication (left to right) → Addition/Subtraction.',
  Percentages: 'Learn the fraction table: 12.5% = 1/8, 16.67% = 1/6, 20% = 1/5, 25% = 1/4, 33.33% = 1/3, 37.5% = 3/8, 62.5% = 5/8.',
  'Profit & Loss': 'Profit and loss % are always on cost price. SP = CP × (100 + p)/100, so CP = SP × 100/(100 + p).',
  Discounts: 'Discount is on marked price. Two discounts a% and b% = one discount of a + b − ab/100.',
  'Ratio & Proportion': 'Split a total in a:b by finding one "part": total ÷ (a + b). Then multiply by the parts you need.',
  Averages: 'Average = total ÷ count. When someone joins or leaves, work with totals, not averages.',
  'Mixtures & Alligation': 'Alligation cross: (dearer − mean) : (mean − cheaper) = cheaper : dearer quantity.',
  'Simple Interest': 'SI = P × R × T ÷ 100. Same interest every year, so 3 years = 3 × one year\'s interest.',
  'Compound Interest': 'For 2 years: CI − SI = P(R/100)². Amount = P(1 + R/100)ⁿ. At 10%: ×1.1, ×1.21, ×1.331.',
  'Time & Work': 'Use per-day work: A does 1/a, B does 1/b, together 1/a + 1/b. Or take LCM of days as total work.',
  'Pipes & Cisterns': 'Same as time & work, but a leak or outlet pipe counts as negative work.',
  'Time, Speed & Distance': 'km/h → m/s: × 5/18. m/s → km/h: × 18/5. Equal distances at x and y: average speed = 2xy/(x + y).',
  Trains: 'Passing a pole: distance = train length. Platform or another train: add the lengths. Opposite directions: add speeds.',
  'Boats & Streams': 'Boat = (down + up) ÷ 2. Stream = (down − up) ÷ 2.',
  Races: '"A beats B by x m" means when A runs the full race, B has run (length − x). Chain the ratios.',
  Ages: 'Let the present ages be x and y; both change by the same number of years. The age difference never changes.',
  'Number System': 'Unit digits repeat in cycles of 4: find the power mod 4 (use 4 when it\'s 0). Trailing zeros of n!: n/5 + n/25 + n/125 …',
  Remainders: 'Find the cycle of remainders of the powers; the power mod (cycle length) tells you where you land.',
  Divisibility: '3 and 9: digit sum. 4: last two digits. 8: last three digits. 11: (sum of odd places) − (sum of even places).',
  'HCF & LCM': 'HCF × LCM = product of the two numbers. "Together again" questions are always LCM.',
  Factors: 'Write N = pᵃ × qᵇ × …; the number of factors is (a + 1)(b + 1)…',
  'Sequences & Series': '1 + 2 + … + n = n(n + 1)/2 · first n odd numbers = n² · first n even numbers = n(n + 1).',
  'Linear Equations': 'With x + y and x − y given: x = (sum + difference)/2, y = (sum − difference)/2, and x² − y² = sum × difference.',
  'Quadratic Equations': 'For x² + bx + c = 0: sum of roots = −b, product = c. Find two numbers with that sum and product.',
  'Quadratic Comparison': 'Solve both equations by factorising. Compare every root of x with every root of y; if they overlap, the relation can\'t be decided.',
  Inequalities: 'Isolate x like an equation. Flip the sign if you multiply or divide by a negative number.',
  Functions: 'Work from the inside out: find g(x) first, then put that value into f.',
  Logarithms: 'logₐ(aⁿ) = n · log(xy) = log x + log y · log(x/y) = log x − log y.',
  Indices: 'aᵐ × aⁿ = aᵐ⁺ⁿ · (aᵐ)ⁿ = aᵐⁿ · write both sides with the same base, then compare the powers.',
  'Squares & Roots': 'A square ends only in 0, 1, 4, 5, 6 or 9. Use the last digit and the nearest known square to guess the root.',
  'AP & GP': 'AP nth term = a + (n − 1)d, sum = n/2 × (first + last). GP nth term = a × rⁿ⁻¹.',
  Geometry: 'Triangle angles add to 180°. A regular n-gon\'s exterior angle is 360/n, so interior = 180 − 360/n.',
  Mensuration: 'Learn the triplets 3-4-5, 5-12-13, 8-15-17, 7-24-25. Circle: area πr², circumference 2πr; with π = 22/7 pick r as a multiple of 7.',
  'Coordinate Geometry': 'Distance = √(Δx² + Δy²). Slope = Δy/Δx. Midpoint = average of the x\'s and of the y\'s.',
  'Permutations & Combinations': 'Order matters → arrangement (nPr). Order doesn\'t → selection (nCr). Repeated letters: divide by each repeat count factorial.',
  Probability: 'P = favourable ÷ total. "At least one" is fastest as 1 − P(none).',
  'Set Theory': 'A or B = A + B − both. Neither = total − (A or B).',
  'Basic Statistics': 'Median: sort first, then take the middle. Mode: most frequent. Range: max − min.',
  Partnership: 'Profit is shared in the ratio of capital × time for each partner.',
  // Logic
  'Number Series': 'Check differences first, then differences of differences, then ×/÷, then squares/cubes ± a constant.',
  'Alphabet Series': 'Number the letters (A = 1 … Z = 26) and EJOTY (5, 10, 15, 20, 25) as checkpoints.',
  'Alphanumeric Series': 'Split letters and numbers into two separate series and solve each.',
  'Number Analogy': 'Test the common rules: square, cube, n² ± 1, n³ ± n, × a constant.',
  'Odd One Out': 'Check prime / square / cube / even-odd / divisibility. The odd one breaks the rule the rest share.',
  'Coding-Decoding': 'Write letter positions under the word and look for a constant shift, reverse alphabet (A = Z, B = Y …) or a sum.',
  'Blood Relations': 'Draw a mini family tree: + for male, − for female, horizontal line for siblings, vertical for parent-child.',
  'Direction Sense': 'Draw it. Right turn = clockwise. Net displacement: add N−S and E−W separately, then use Pythagoras.',
  Ranking: 'Total = left rank + right rank − 1. Between two people = (difference in ranks) − 1.',
  'Linear Arrangement': 'Start with the fixed clue (ends, exact positions), then "immediately next to", then "between".',
  'Circular Arrangement': 'Facing the centre, your left is clockwise. Fix one person and place others relative to them.',
  Scheduling: 'Draw the days as slots. Place fixed days first, then "before/after" clues.',
  'Distribution Puzzles': 'Make a grid of people × attributes. Tick facts, cross the "not" clues, and look for the only empty box left.',
  'Selection & Grouping': 'Test each option against the rules in order; reject it at the first rule it breaks.',
  Syllogisms: 'A conclusion follows only if it holds in EVERY Venn diagram the statements allow. "Some" can mean all.',
  'Coded Inequalities': 'Chain the signs between the two letters in the conclusion. Any opposite signs (> and <) in the chain → no relation.',
  'Data Sufficiency': 'You only need to know IF a unique answer exists, never the answer itself. Check each statement alone, then together.',
  'Conditional Logic': '"If P then Q" does not mean "if not P then not Q". Only "not Q → not P" is guaranteed.',
  'Critical Reasoning': 'A strong argument is directly linked to the question and important; "everyone does it" and personal feelings are weak.',
  Clocks: 'Angle = |30H − 5.5M|. Mirror time = 11:60 − shown time (12:00 − shown time).',
  Calendars: 'Odd days: a normal year shifts the weekday by 1, a leap year by 2. Divide days by 7 and count the remainder forward.',
  // DI
  'Bar Graphs': 'Read the scale first. For % change, divide by the earlier (starting) value.',
  'Line Graphs': 'The steepest segment is the biggest change. Gaps between two lines show differences.',
  'Pie Charts': '1% of a pie = 3.6°. Convert to percentages before comparing slices.',
  Tables: 'Add rows or columns only for what is asked; estimate first to rule out options.',
  Caselets: 'Turn the paragraph into a small table before you calculate anything.',
  'Missing Data': 'Total = average × count; subtract what you know to find the missing value.',
  'Comparative DI': 'Compare item by item; ties count as "not more".',
  'Multi-step DI': 'If shares stay the same, the extra amount for an item = its share × the extra total.',
  // Verbal
  Synonyms: 'Use the word in a sentence, then swap in each option. The one that keeps the meaning is the answer.',
  Antonyms: 'Decide if the word is positive or negative first; the opposite has the other tone.',
  Vocabulary: 'Break the word into roots: bene = good, mal = bad, chron = time, phil = love, port = carry.',
  'Word Analogies': 'Say the relation as a sentence ("a flock is a group of birds") and test it on the second pair.',
  'Sentence Completion': 'Look for clue words after a semicolon or "but", "although", "because": they tell you the tone of the blank.',
  'Error Spotting': 'Check subject-verb agreement, tense, articles, prepositions and pronouns, in that order.',
  Spelling: 'Watch for double letters (accommodate, committee), -ance/-ence and ie/ei.',
  Idioms: 'Idioms are never literal. Think of how you\'d use it in a sentence about people, not objects.',
  'One-word Substitution': 'Learn word families: -logy (study of), -phobia (fear), -archy (rule), omni- (all).',
  'Para Jumbles': 'Find the opening sentence (introduces the subject, no pronoun), then follow pronouns, time words and cause → effect.',
  'Reading Comprehension': 'The right option restates the passage. Wrong options exaggerate, add new ideas or twist a detail.',
  // Visual
  'Cubes & Dice': 'Numbers seen together on one view are adjacent, never opposite. Painted cube n×n×n: one face = 6(n − 2)², two faces = 12(n − 2), three = 8.',
  'Figure Analogy': 'Name the change from figure 1 to 2 (turn, fill, count, shape) and apply exactly that change.',
  'Figure Counting': 'Squares in an n×n grid = 1² + 2² + … + n². Rectangles = (nC2 of lines)²; for a 2×2 grid: 5 squares, 9 rectangles.',
  'Figure Series': 'Track one property at a time: rotation, fill, count, size.',
  'Matrix Puzzles': 'Look across rows first, then down columns: sum, product or difference.',
  'Mirror & Water Images': 'Mirror image flips left-right; water image flips top-bottom.',
  'Odd Figure Out': 'Count sides, fills and directions; the odd one breaks the shared property.',
  'Paper Folding': 'Each fold doubles the layers, so holes = holes punched × 2ⁿ, where n is the number of folds.',
  'Pattern Completion': 'Find the repeating block and its length, then count forward.',
  Rotation: 'Add clockwise turns, subtract anticlockwise ones, and reduce mod 360°.',
  'Symbol Puzzles': 'Solve the line with a single symbol first, then substitute downward.',
  'Visual Counting': 'Scan row by row and count in fives; don\'t try to count the whole grid at once.',
};
