import { StyleSheet, Platform } from 'react-native';

export const PALETTE = {
  light: {
    bg: '#FAF6F1', card: '#FFFFFF', ink: '#1E1932', muted: '#857C99', line: '#EEE6DD',
    accent: '#FF7A45', accentInk: '#FFFFFF', accentSoft: '#FFE8DC',
    good: '#23B26D', goodSoft: '#DDF7EA', bad: '#F0506E', badSoft: '#FFE3E8',
    rival: '#5B7CFA', rivalSoft: '#E6ECFF', gold: '#FFB400', goldSoft: '#FFF3D1', lilac: '#F1EAFF', mint: '#DDF7EA', sky: '#E2F3FF',
    deep: '#2D2360', deepInk: '#FFFFFF', deepSoft: '#EDE9FF',
    shadow: '#B08968', overlay: 'rgba(43,33,64,0.45)', tab: '#FFFFFF',
  },
  dark: {
    bg: '#110E20', card: '#1C1832', ink: '#F5F1FF', muted: '#A39BC2', line: '#2B2547',
    accent: '#FF8A5B', accentInk: '#241006', accentSoft: '#3D2630',
    good: '#4ED492', goodSoft: '#173A2B', bad: '#FF7390', badSoft: '#43202C',
    rival: '#8FA6FF', rivalSoft: '#262E55', gold: '#FFC940', goldSoft: '#3A3020', lilac: '#2C2450', mint: '#173A2B', sky: '#1C2E45',
    deep: '#3B2F86', deepInk: '#FFFFFF', deepSoft: '#2A2352',
    shadow: '#000000', overlay: 'rgba(0,0,0,0.6)', tab: '#1D1833',
  },
};
export const F = { m: 'Baloo2_500Medium', s: 'Baloo2_600SemiBold', b: 'Baloo2_700Bold', x: 'Baloo2_800ExtraBold' };
export const CONFETTI = ['#FF7A45', '#FFB400', '#23B26D', '#5B7CFA', '#F06FB1', '#9B7BFF'];

export function makeStyles(C) {
  const shadow = { shadowColor: C.shadow, shadowOpacity: 0.09, shadowRadius: 22, shadowOffset: { width: 0, height: 10 }, elevation: 4 };
  const edge = { borderWidth: 1, borderColor: C.line };
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: C.bg },
    wrap: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 32, gap: 16, maxWidth: 480, width: '100%', alignSelf: 'center' },
    top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    logo: { fontFamily: F.x, fontSize: 36, color: C.ink, lineHeight: 46 },
    logoSmall: { fontFamily: F.x, fontSize: 22, color: C.ink, lineHeight: 28 },
    h1: { fontFamily: F.x, fontSize: 28, color: C.ink, lineHeight: 36 },
    h2: { fontFamily: F.b, fontSize: 20, color: C.ink, lineHeight: 28 },
    small: { fontFamily: F.m, fontSize: 13, color: C.muted, lineHeight: 19 },
    label: { fontFamily: F.b, fontSize: 11, letterSpacing: 1.3, color: C.muted, lineHeight: 16 },
    pill: { backgroundColor: C.card, borderRadius: 99, paddingVertical: 6, paddingHorizontal: 12, ...shadow },
    pillText: { fontFamily: F.x, fontSize: 15, color: C.ink, lineHeight: 20 },
    iconBtn: { width: 42, height: 42, borderRadius: 21, backgroundColor: C.card, alignItems: 'center', justifyContent: 'center', ...shadow },
    iconBtnText: { fontSize: 18, color: C.ink },
    card: { backgroundColor: C.card, borderRadius: 26, padding: 18, gap: 12, ...edge, ...shadow },
    witRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
    witOwl: { fontSize: 38 },
    bubble: { flex: 1, backgroundColor: C.card, borderRadius: 18, borderBottomLeftRadius: 4, paddingVertical: 10, paddingHorizontal: 14, ...shadow },
    bubbleText: { fontFamily: F.s, fontSize: 14, color: C.ink, lineHeight: 20 },
    rankRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    badge: { width: 56, height: 56, borderRadius: 28, backgroundColor: C.accentSoft, alignItems: 'center', justifyContent: 'center' },
    tier: { fontFamily: F.x, fontSize: 24, color: C.ink, lineHeight: 30 },
    tierSmall: { fontFamily: F.x, fontSize: 19, color: C.ink, lineHeight: 25 },
    score: { fontFamily: F.x, fontSize: 28, color: C.accent, lineHeight: 34 },
    meter: { height: 12, backgroundColor: C.line, borderRadius: 99, overflow: 'hidden' },
    meterFill: { height: '100%', backgroundColor: C.accent, borderRadius: 99 },
    xpMeter: { flex: 1, height: 8, backgroundColor: C.line, borderRadius: 99, overflow: 'hidden' },
    xpFill: { height: '100%', backgroundColor: C.rival, borderRadius: 99 },
    lvChip: { fontFamily: F.x, fontSize: 12, color: C.rival, backgroundColor: C.rivalSoft, paddingVertical: 2, paddingHorizontal: 9, borderRadius: 99, overflow: 'hidden' },
    ladder: { flexDirection: 'row', justifyContent: 'space-between' },
    step: { alignItems: 'center', gap: 2 },
    stepDot: { width: 34, height: 34, borderRadius: 17, borderWidth: 2, borderColor: C.line, alignItems: 'center', justifyContent: 'center', backgroundColor: C.bg },
    stepText: { fontFamily: F.b, fontSize: 11, color: C.muted },
    primary: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.accent, borderRadius: 28, paddingVertical: 22, paddingHorizontal: 20, overflow: 'hidden', ...shadow, shadowColor: C.accent, shadowOpacity: 0.35, shadowRadius: 20 },
    primaryTitle: { fontFamily: F.x, fontSize: 26, color: C.accentInk, lineHeight: 32 },
    primaryText: { fontFamily: F.s, fontSize: 13, color: C.accentInk, opacity: 0.92 },
    playDot: { width: 46, height: 46, borderRadius: 23, backgroundColor: 'rgba(255,255,255,0.25)', alignItems: 'center', justifyContent: 'center' },
    playDotText: { color: C.accentInk, fontSize: 18 },
    threeCol: { flexDirection: 'row', gap: 10 },
    tile: { flex: 1, borderRadius: 24, padding: 14, gap: 2, minHeight: 118, ...edge },
    tileIcon: { fontSize: 25 },
    tileTitle: { fontFamily: F.x, fontSize: 16, color: C.ink, lineHeight: 21 },
    tileSub: { fontFamily: F.m, fontSize: 12, color: C.muted, lineHeight: 16 },
    chip: { fontFamily: F.b, fontSize: 13, color: C.ink, backgroundColor: C.accentSoft, paddingVertical: 5, paddingHorizontal: 12, borderRadius: 99, overflow: 'hidden' },
    stat: { flex: 1, alignItems: 'center' },
    statValue: { fontFamily: F.x, fontSize: 20, color: C.ink, lineHeight: 26 },
    statLabel: { fontFamily: F.m, fontSize: 12, color: C.muted },
    settingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    settingText: { fontFamily: F.b, fontSize: 16, color: C.ink },
    freezeBadge: { backgroundColor: C.rivalSoft, borderRadius: 99, paddingVertical: 4, paddingHorizontal: 10 },
    freezeText: { fontFamily: F.x, fontSize: 13, color: C.ink },
    freezeBtn: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.rivalSoft, borderRadius: 18, paddingVertical: 10, paddingHorizontal: 12 },
    freezeTitle: { fontFamily: F.x, fontSize: 15, color: C.ink, lineHeight: 20 },
    miniBtn: { backgroundColor: C.accent, borderRadius: 14, paddingVertical: 8, paddingHorizontal: 14 },
    miniBtnText: { fontFamily: F.x, fontSize: 14, color: C.accentInk },
    missionRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    missionDot: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: C.bg, borderWidth: 2, borderColor: C.line },
    missionText: { fontFamily: F.b, fontSize: 14, color: C.ink, lineHeight: 19 },
    missionBar: { height: 6, backgroundColor: C.line, borderRadius: 99, overflow: 'hidden', marginTop: 3 },
    missionFill: { height: '100%', backgroundColor: C.good, borderRadius: 99 },
    missionXp: { fontFamily: F.x, fontSize: 12, color: C.rival },
    tabs: { flexDirection: 'row', gap: 6, paddingHorizontal: 12, paddingTop: 8, paddingBottom: 8, backgroundColor: C.tab, borderTopWidth: 1, borderTopColor: C.line },
    tab: { flex: 1, alignItems: 'center', paddingVertical: 6, borderRadius: 16 },
    tabText: { fontFamily: F.b, fontSize: 12, color: C.muted },
    gameTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    clock: { alignSelf: 'flex-start', backgroundColor: C.card, borderWidth: 2, borderColor: C.line, borderRadius: 14, paddingVertical: 2, paddingHorizontal: 12 },
    clockText: { fontFamily: F.x, fontSize: 18, color: C.ink, lineHeight: 26 },
    bar: { height: 8, backgroundColor: C.line, borderRadius: 99, overflow: 'hidden' },
    barFill: { height: '100%', backgroundColor: C.accent, borderRadius: 99 },
    hud: { flexDirection: 'row', gap: 10 },
    player: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 20, paddingVertical: 8, paddingHorizontal: 10 },
    who: { fontFamily: F.b, fontSize: 13, color: C.ink },
    hudScore: { fontFamily: F.x, fontSize: 28, lineHeight: 34 },
    plusOne: { position: 'absolute', right: 0, top: -6, fontFamily: F.x, fontSize: 18, color: C.good },
    qCard: { backgroundColor: C.card, borderRadius: 26, padding: 18, gap: 10, minHeight: 160, justifyContent: 'center', ...shadow },
    qTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
    typeChip: { fontFamily: F.b, fontSize: 12, color: C.accent, backgroundColor: C.accentSoft, paddingVertical: 3, paddingHorizontal: 10, borderRadius: 99, overflow: 'hidden' },
    levelChip: { fontFamily: F.b, fontSize: 11, color: C.muted, backgroundColor: C.bg, paddingVertical: 3, paddingHorizontal: 8, borderRadius: 99, overflow: 'hidden' },
    combo: { fontFamily: F.x, fontSize: 15, color: C.accent },
    prompt: { fontFamily: F.b, fontSize: 18, color: C.ink, lineHeight: 26 },
    emph: { fontFamily: F.x, fontSize: 26, color: C.accent, textAlign: 'center', lineHeight: 34, paddingTop: 2 },
    emphSmall: { fontSize: 19, lineHeight: 28 },
    emphEmoji: { fontSize: 32, lineHeight: 44, letterSpacing: 2 },
    passage: { backgroundColor: C.card, borderRadius: 20, padding: 16, borderLeftWidth: 4, borderLeftColor: C.rival, ...shadow },
    passageText: { fontFamily: F.m, fontSize: 15, color: C.ink, lineHeight: 23 },
    visTitle: { fontFamily: F.b, fontSize: 12, color: C.muted, textAlign: 'center', letterSpacing: 0.5 },
    opts: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    opt: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 64, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: C.card, borderWidth: 1.5, borderColor: C.line, ...shadow },
    optRight: { borderColor: C.good, backgroundColor: C.goodSoft, borderWidth: 2 },
    optWrong: { borderColor: C.bad, backgroundColor: C.badSoft, borderWidth: 2 },
    optLetter: { width: 26, height: 26, borderRadius: 13, textAlign: 'center', fontFamily: F.x, fontSize: 13, lineHeight: 26, color: C.muted, backgroundColor: C.bg, overflow: 'hidden' },
    optText: { flex: 1, fontFamily: F.x, fontSize: 21, color: C.ink, lineHeight: 28 },
    optWord: { fontSize: 16, lineHeight: 22, fontFamily: F.b },
    optEmoji: { fontSize: 30, lineHeight: 38, textAlign: 'center' },
    fb: { minHeight: 22, fontFamily: F.b, fontSize: 14, textAlign: 'center', color: C.muted },
    fbCard: { borderRadius: 20, padding: 16, gap: 8, borderWidth: 2 },
    nextBar: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 16, paddingTop: 12, backgroundColor: C.bg, borderTopWidth: 1, borderColor: C.line, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 14, shadowOffset: { width: 0, height: -4 }, elevation: 10 },
    frameGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    frameTile: { width: '31.6%', alignItems: 'center', gap: 4, paddingVertical: 14, paddingHorizontal: 6, borderRadius: 20, backgroundColor: C.card, borderWidth: 2, borderColor: 'transparent', ...edge },
    frameName: { fontFamily: F.b, fontSize: 13, color: C.ink, marginTop: 8 },
    frameStatus: { fontFamily: F.m, fontSize: 11.5, color: C.muted },
    quote: { position: 'absolute', left: 16, right: 16, backgroundColor: C.card, borderRadius: 22, paddingVertical: 10, paddingHorizontal: 14, borderWidth: 1, borderColor: C.line, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 14 },
    quoteText: { fontFamily: F.b, fontSize: 15, lineHeight: 21, color: C.ink },
    mistake: { borderRadius: 18, padding: 14, gap: 6, backgroundColor: C.bg, borderWidth: 1, borderColor: C.line },
    mistakeQ: { fontFamily: F.b, fontSize: 15, lineHeight: 21, color: C.ink },
    fbTitle: { fontFamily: F.x, fontSize: 18, lineHeight: 24 },
    fbText: { fontFamily: F.m, fontSize: 14, color: C.ink, lineHeight: 21 },
    witPop: { position: 'absolute', top: -16, right: 12, flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.ink, borderRadius: 99, paddingVertical: 4, paddingHorizontal: 12, zIndex: 5 },
    witPopText: { fontFamily: F.x, fontSize: 13, color: C.bg },
    resultCard: { backgroundColor: C.card, borderRadius: 28, padding: 20, gap: 12, borderWidth: 1, borderColor: C.line, ...shadow },
    resultTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    trophy: { fontSize: 72, textAlign: 'center' },
    resTitle: { fontFamily: F.x, fontSize: 32, color: C.ink, textAlign: 'center', lineHeight: 40 },
    versus: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    vsSide: { flex: 1, alignItems: 'center', gap: 2 },
    vsScore: { fontFamily: F.x, fontSize: 44, lineHeight: 52 },
    vsDash: { fontFamily: F.x, fontSize: 18, color: C.muted },
    marks: { fontSize: 28, letterSpacing: 2 },
    resultFoot: { flexDirection: 'row', justifyContent: 'center', gap: 8, flexWrap: 'wrap' },
    cta: { fontFamily: F.s, fontSize: 13, color: C.muted, textAlign: 'center' },
    bigBadge: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 18, paddingVertical: 10, paddingHorizontal: 14, borderWidth: 2 },
    bigBadgeText: { fontFamily: F.x, fontSize: 16, color: C.ink, lineHeight: 21 },
    catRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    catName: { width: 64, fontFamily: F.b, fontSize: 13, color: C.ink },
    catBar: { flex: 1, height: 10, backgroundColor: C.line, borderRadius: 99, overflow: 'hidden' },
    catFill: { height: '100%', borderRadius: 99 },
    catVal: { width: 44, textAlign: 'right', fontFamily: F.x, fontSize: 13, color: C.ink },
    btn: { backgroundColor: C.accent, borderRadius: 20, paddingVertical: 16, alignItems: 'center', overflow: 'hidden', ...shadow, shadowColor: C.accent, shadowOpacity: 0.3, shadowRadius: 16 },
    btnText: { fontFamily: F.x, color: C.accentInk, fontSize: 18, lineHeight: 24 },
    btnGhost: { borderRadius: 20, paddingVertical: 14, paddingHorizontal: 8, alignItems: 'center', backgroundColor: C.card, borderWidth: 1.5, borderColor: C.line },
    btnGhostText: { fontFamily: F.b, color: C.ink, fontSize: 15, lineHeight: 21, textAlign: 'center' },
    termsH: { fontFamily: F.b, fontSize: 15, color: C.ink, lineHeight: 21 },
    termsB: { fontFamily: F.m, fontSize: 14, color: C.muted, lineHeight: 20 },
    checkRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 4 },
    checkbox: { width: 28, height: 28, borderRadius: 9, borderWidth: 2, borderColor: C.muted, alignItems: 'center', justifyContent: 'center' },
    checkText: { flex: 1, fontFamily: F.s, fontSize: 14, color: C.ink, lineHeight: 20 },
    input: { fontFamily: F.b, fontSize: 20, color: C.ink, backgroundColor: C.bg, borderRadius: 16, paddingHorizontal: 14, paddingVertical: Platform.OS === 'ios' ? 12 : 8, borderWidth: 2, borderColor: C.line },
    avGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around', rowGap: 12, maxWidth: 320, alignSelf: 'center', width: '100%' },
    avCell: { width: 68, alignItems: 'center' },
    boardRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: C.line, borderRadius: 14 },
    boardRank: { width: 28, fontFamily: F.x, fontSize: 16, color: C.muted, textAlign: 'center' },
    boardName: { flex: 1, fontFamily: F.b, fontSize: 15, color: C.ink },
    boardScore: { fontFamily: F.x, fontSize: 18, color: C.ink },
    foot: { fontFamily: F.m, fontSize: 12, color: C.muted, textAlign: 'center' },
    modalBack: { backgroundColor: C.overlay, alignItems: 'center', justifyContent: 'center', padding: 24 },
    modal: { width: '100%', maxWidth: 380, backgroundColor: C.card, borderRadius: 28, padding: 22, gap: 12 },
    modeCard: { borderRadius: 26, padding: 20, gap: 6, backgroundColor: C.deep, overflow: 'hidden', ...shadow },
    modeTitle: { fontFamily: F.x, fontSize: 24, color: C.deepInk, lineHeight: 30 },
    modeText: { fontFamily: F.s, fontSize: 14, color: C.deepInk, opacity: 0.85, lineHeight: 20 },
    achGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    achCell: { width: '31%', flexGrow: 1, alignItems: 'center', borderRadius: 16, paddingVertical: 10, paddingHorizontal: 4, backgroundColor: C.bg, gap: 2 },
    achName: { fontFamily: F.b, fontSize: 11, color: C.ink, textAlign: 'center', lineHeight: 14 },
    catChip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 16, paddingVertical: 10, paddingHorizontal: 12, backgroundColor: C.card, borderWidth: 2, borderColor: C.line },
    // --- v5 additions ---
    brandRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    infoDot: { fontFamily: F.x, fontSize: 12, color: C.muted, width: 20, height: 20, borderRadius: 10, textAlign: 'center', lineHeight: 20, backgroundColor: C.bg, overflow: 'hidden' },
    sheetBack: { backgroundColor: C.overlay, justifyContent: 'flex-end' },
    sheet: { backgroundColor: C.card, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, gap: 12, width: '100%', maxWidth: 520, alignSelf: 'center' },
    sheetTitle: { fontFamily: F.x, fontSize: 22, color: C.ink, lineHeight: 28 },
    sheetBody: { fontFamily: F.m, fontSize: 15, color: C.ink, lineHeight: 23 },
    hint: { position: 'absolute', alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.ink, borderRadius: 99, paddingVertical: 8, paddingHorizontal: 16, ...shadow },
    hintText: { fontFamily: F.x, fontSize: 14, color: C.bg },
    reactRow: { flexDirection: 'row', justifyContent: 'center', gap: 8 },
    reactBtn: { width: 40, height: 34, borderRadius: 12, backgroundColor: C.card, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: C.line },
    floatEmoji: { position: 'absolute', bottom: 46 },
    matchWrap: { alignItems: 'center', gap: 16, paddingTop: 24 },
    matchTitle: { fontFamily: F.x, fontSize: 26, color: C.ink, textAlign: 'center', lineHeight: 32 },
    vsBig: { fontFamily: F.x, fontSize: 40, color: C.accent, lineHeight: 48 },
    countdown: { fontFamily: F.x, fontSize: 96, color: C.accent, lineHeight: 110, textAlign: 'center' },
    hearts: { flexDirection: 'row', gap: 2 },
    modeRow: { flexDirection: 'row', gap: 10 },
    modeMini: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 20, padding: 12, backgroundColor: C.card, borderWidth: 2, borderColor: C.line },
    modeMiniTitle: { fontFamily: F.x, fontSize: 15, color: C.ink, lineHeight: 20 },
    tabsBar: { flexDirection: 'row', gap: 4, paddingHorizontal: 12, paddingTop: 8, backgroundColor: C.tab, borderTopLeftRadius: 26, borderTopRightRadius: 26, ...edge, borderBottomWidth: 0, shadowColor: '#000', shadowOpacity: 0.07, shadowRadius: 18, shadowOffset: { width: 0, height: -4 }, elevation: 12 },
    tabBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 6, borderRadius: 16, minHeight: 54, gap: 2 },
    tabLabel: { fontFamily: F.b, fontSize: 12, color: C.muted, lineHeight: 16 },
    subTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    subTab: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 7, paddingHorizontal: 11, borderRadius: 99, backgroundColor: C.card, borderWidth: 2, borderColor: C.line },
    subTabText: { fontFamily: F.b, fontSize: 13, color: C.ink },
    avTabs: { flexDirection: 'row', gap: 6, alignSelf: 'center' },
    feedbackInput: { fontFamily: F.m, fontSize: 15, color: C.ink, backgroundColor: C.bg, borderRadius: 16, padding: 12, minHeight: 96, textAlignVertical: 'top', borderWidth: 2, borderColor: C.line },
  });
}
